#!/bin/bash
# suggestions wrapper
# 
[ -z "$1" ] && echo "suggestion google|youtube|deezer|lastfm|books" && exit 1
API="$1"
#Note: full path
handler=$HOME/.local/bin/search/handler
case "$API" in 
"google") prompt="Google" ;;
"deezer") prompt="Deezer" ;;
"youtube") prompt="Youtube" ;;
"lastfm") prompt="Spotify" ;; 
"books") prompt="Books" ;; 
*) echo "Api not recognized" && exit 1 ;;
esac 
###############
logfile="$(dirname $handler)/logfile.tmp"
printf "$API" > "$logfile"
rofi -modi blocks -show blocks -blocks-wrap $handler -display-blocks "$prompt" &>/dev/null
result="$(cat $logfile)"
echo "$result" && rm "$logfile"
exit 0